export const mainConfig = {
    "burkinafaso": {
        "Name": "Burkina Faso",
        "TLC": "BFA",
        "Adm1": "Region",
        "Adm2": "Province",
        "Center": [12.7, -1.8],
        "Zoom": [6],
        "DistrictOnly": [],
        "NoR1": [],
        "NoR2": [],
        "indicators": {
            "LBW": {
                "Indicator":"Low birth weight",
                "Theme":"Child Health",
                "Remark":"",
                "Min":0.0,
                "Max":42.5,
                "Delta":2.5,
                "CHMin":-25.0,
                "CHMax":25.0,
                "CHDelta":2.5,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Min_diet": {
                "Indicator":"Minimum acceptable diet",
                "Theme":"Nutrition",
                "Remark":"",
                "Min":0.0,
                "Max":48.0,
                "Delta":3.0,
                "CHMin":-32.0,
                "CHMax":24.0,
                "CHDelta":4.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Sever_wast": {
                "Indicator":"Prevalence of severe wasting",
                "Theme":"Nutrition",
                "Remark":"",
                "Min":0.0,
                "Max":42.5,
                "Delta":2.5,
                "CHMin":-22.5,
                "CHMax":25.0,
                "CHDelta":2.5,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Teen_Pregn": {
                "Indicator":"Teenage pregnancies",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":40.0,
                "Delta":2.5,
                "CHMin":-27.5,
                "CHMax":17.5,
                "CHDelta":2.5,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "U_Pregn": {
                "Indicator":"Unwanted births",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":40.0,
                "Delta":2.5,
                "CHMin":-27.5,
                "CHMax":17.5,
                "CHDelta":2.5,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Anaemia": {
                "Indicator":"Prevalence of anaemia ",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":15.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-35.0,
                "CHMax":45.0,
                "CHDelta":5.0,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "ANC_4plus": {
                "Indicator":"Antenatal care (4+ visits)",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-70.0,
                "CHMax":70.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "ANC_blood": {
                "Indicator":"Antenatal care (blood screening)",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":30.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-15.0,
                "CHMax":55.0,
                "CHDelta":5.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "ANC_suppl": {
                "Indicator":"Antenatal care (supplements)",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-70.0,
                "CHMax":70.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "ANC_timing": {
                "Indicator":"Antenatal care (timing)",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-30.0,
                "CHMax":70.0,
                "CHDelta":5.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "ANC_urine": {
                "Indicator":"Antenatal care (urine screening)",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-70.0,
                "CHMax":70.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Breastfeed": {
                "Indicator":"Exclusive breastfeeding",
                "Theme":"Nutrition",
                "Remark":"",
                "Min":20.0,
                "Max":90.0,
                "Delta":5.0,
                "CHMin":-25.0,
                "CHMax":75.0,
                "CHDelta":5.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "C_Prev": {
                "Indicator":"Modern contraceptive use",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":4.0,
                "Max":72.0,
                "Delta":4.0,
                "CHMin":-20.0,
                "CHMax":52.0,
                "CHDelta":4.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Child_m": {
                "Indicator":"Child marriage",
                "Theme":"Child Protection",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-70.0,
                "CHMax":70.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Labour_fem": {
                "Indicator":"Female labour force participation",
                "Theme":"Livelihoods",
                "Remark":"",
                "Min":4.0,
                "Max":84.0,
                "Delta":4.0,
                "CHMin":-24.0,
                "CHMax":44.0,
                "CHDelta":4.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "NAR_prim": {
                "Indicator":"Net primary school attendance",
                "Theme":"Education",
                "Remark":"",
                "Min":62.0,
                "Max":98.0,
                "Delta":2.0,
                "CHMin":-80.0,
                "CHMax":32.0,
                "CHDelta":4.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "NAR_sec": {
                "Indicator":"Net secondary school attendance",
                "Theme":"Education",
                "Remark":"",
                "Min":28.0,
                "Max":96.0,
                "Delta":4.0,
                "CHMin":-20.0,
                "CHMax":32.0,
                "CHDelta":4.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Stunting": {
                "Indicator":"Prevalence of stunting",
                "Theme":"Nutrition",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-70.0,
                "CHMax":70.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Wash_sanit": {
                "Indicator":"WASH coverage (sanitation)",
                "Theme":"WASH",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-60.0,
                "CHMax":90.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Wash_water": {
                "Indicator":"WASH coverage (water)",
                "Theme":"WASH",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-80.0,
                "CHMax":80.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "NMR": {
                "Indicator":"Neonatal mortality rate",
                "Theme":"Child Health",
                "Remark":"For this indicator, district estimates only were produced. The indicators shown here are rare events, highlighting the necessity for cautious interpretation and utilization of findings, given the limited district-level sample sizes.",
                "Min":0,
                "Max":50,
                "Delta":2.5,
                "CHMin":-25,
                "CHMax":25,
                "CHDelta":2.5,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"District",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Unsafe_Ab": {
                "Indicator":"Unsafe abortions ",
                "Theme":"Reproductive Health",
                "Remark":"For this indicator, district estimates only were produced. The indicators shown here are rare events, highlighting the necessity for cautious interpretation and utilization of findings, given the limited district-level sample sizes.",
                "Min":0,
                "Max":60,
                "Delta":3,
                "CHMin":-30,
                "CHMax":30,
                "CHDelta":3,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"District",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "CHMR": {
                "Indicator":"Child mortality rate",
                "Theme":"Child Health",
                "Remark":"For this indicator, district estimates only were produced. The indicators shown here are rare events, highlighting the necessity for cautious interpretation and utilization of findings, given the limited district-level sample sizes.",
                "Min":0,
                "Max":20,
                "Delta":1,
                "CHMin":-10.0,
                "CHMax":10.0,
                "CHDelta":1,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"District",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Lab_child": {
                "Indicator":"Prevalence of child workers",
                "Theme":"Child Protection",
                "Remark":"For child worker, census estimates were used to calculate the indicator, and only had one point in time was available.",
                "Min":0.0,
                "Max":10.0,
                "Delta":0.05,
                "CHMin":-5.0,
                "CHMax":5.0,
                "CHDelta":-0.05,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"District",
                "R1":"Census",
                "R2":"No data",
                "Y1":"2011",
                "Y2":null
            },
            "Stillbirth": {
                "Indicator":"Still birth rate",
                "Theme":"Child Health",
                "Remark":"For this indicator, district estimates only were produced. The indicators shown here are rare events, highlighting the necessity for cautious interpretation and utilization of findings, given the limited district-level sample sizes.",
                "Min":2.0,
                "Max":40.0,
                "Delta":2.0,
                "CHMin":-20.0,
                "CHMax":20.0,
                "CHDelta":2.0,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"District",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
        }
    },
    "india": {
        "Name": "India",
        "TLC": "IND",
        "Adm1": "State",
        "Adm2": "District",
        "Center": [22.9, 79.6],
        "Zoom": [4],
        "DistrictOnly": ['NMR', 'Unsafe_Ab', 'CHMR', 'Lab_child', 'Stillbirth'],
        "NoR1": [],
        "NoR2": ['Lab_child'],
        "indicators": {
            "LBW": {
                "Indicator":"Low birth weight",
                "Theme":"Child Health",
                "Remark":"",
                "Min":0.0,
                "Max":42.5,
                "Delta":2.5,
                "CHMin":-25.0,
                "CHMax":25.0,
                "CHDelta":2.5,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Min_diet": {
                "Indicator":"Minimum acceptable diet",
                "Theme":"Nutrition",
                "Remark":"",
                "Min":0.0,
                "Max":48.0,
                "Delta":3.0,
                "CHMin":-32.0,
                "CHMax":24.0,
                "CHDelta":4.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Sever_wast": {
                "Indicator":"Prevalence of severe wasting",
                "Theme":"Nutrition",
                "Remark":"",
                "Min":0.0,
                "Max":42.5,
                "Delta":2.5,
                "CHMin":-22.5,
                "CHMax":25.0,
                "CHDelta":2.5,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Teen_Pregn": {
                "Indicator":"Teenage pregnancies",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":40.0,
                "Delta":2.5,
                "CHMin":-27.5,
                "CHMax":17.5,
                "CHDelta":2.5,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "U_Pregn": {
                "Indicator":"Unwanted births",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":40.0,
                "Delta":2.5,
                "CHMin":-27.5,
                "CHMax":17.5,
                "CHDelta":2.5,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Anaemia": {
                "Indicator":"Prevalence of anaemia ",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":15.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-35.0,
                "CHMax":45.0,
                "CHDelta":5.0,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "ANC_4plus": {
                "Indicator":"Antenatal care (4+ visits)",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-70.0,
                "CHMax":70.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "ANC_blood": {
                "Indicator":"Antenatal care (blood screening)",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":30.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-15.0,
                "CHMax":55.0,
                "CHDelta":5.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "ANC_suppl": {
                "Indicator":"Antenatal care (supplements)",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-70.0,
                "CHMax":70.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "ANC_timing": {
                "Indicator":"Antenatal care (timing)",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-30.0,
                "CHMax":70.0,
                "CHDelta":5.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "ANC_urine": {
                "Indicator":"Antenatal care (urine screening)",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-70.0,
                "CHMax":70.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Breastfeed": {
                "Indicator":"Exclusive breastfeeding",
                "Theme":"Nutrition",
                "Remark":"",
                "Min":20.0,
                "Max":90.0,
                "Delta":5.0,
                "CHMin":-25.0,
                "CHMax":75.0,
                "CHDelta":5.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "C_Prev": {
                "Indicator":"Modern contraceptive use",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":4.0,
                "Max":72.0,
                "Delta":4.0,
                "CHMin":-20.0,
                "CHMax":52.0,
                "CHDelta":4.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Child_m": {
                "Indicator":"Child marriage",
                "Theme":"Child Protection",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-70.0,
                "CHMax":70.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Labour_fem": {
                "Indicator":"Female labour force participation",
                "Theme":"Livelihoods",
                "Remark":"",
                "Min":4.0,
                "Max":84.0,
                "Delta":4.0,
                "CHMin":-24.0,
                "CHMax":44.0,
                "CHDelta":4.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "NAR_prim": {
                "Indicator":"Net primary school attendance",
                "Theme":"Education",
                "Remark":"",
                "Min":62.0,
                "Max":98.0,
                "Delta":2.0,
                "CHMin":-80.0,
                "CHMax":32.0,
                "CHDelta":4.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "NAR_sec": {
                "Indicator":"Net secondary school attendance",
                "Theme":"Education",
                "Remark":"",
                "Min":28.0,
                "Max":96.0,
                "Delta":4.0,
                "CHMin":-20.0,
                "CHMax":32.0,
                "CHDelta":4.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Stunting": {
                "Indicator":"Prevalence of stunting",
                "Theme":"Nutrition",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-70.0,
                "CHMax":70.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Wash_sanit": {
                "Indicator":"WASH coverage (sanitation)",
                "Theme":"WASH",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-60.0,
                "CHMax":90.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Wash_water": {
                "Indicator":"WASH coverage (water)",
                "Theme":"WASH",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-80.0,
                "CHMax":80.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "NMR": {
                "Indicator":"Neonatal mortality rate",
                "Theme":"Child Health",
                "Remark":"For this indicator, district estimates only were produced. The indicators shown here are rare events, highlighting the necessity for cautious interpretation and utilization of findings, given the limited district-level sample sizes.",
                "Min":0,
                "Max":50,
                "Delta":2.5,
                "CHMin":-25,
                "CHMax":25,
                "CHDelta":2.5,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"District",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Unsafe_Ab": {
                "Indicator":"Unsafe abortions ",
                "Theme":"Reproductive Health",
                "Remark":"For this indicator, district estimates only were produced. The indicators shown here are rare events, highlighting the necessity for cautious interpretation and utilization of findings, given the limited district-level sample sizes.",
                "Min":0,
                "Max":60,
                "Delta":3,
                "CHMin":-30,
                "CHMax":30,
                "CHDelta":3,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"District",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "CHMR": {
                "Indicator":"Child mortality rate",
                "Theme":"Child Health",
                "Remark":"For this indicator, district estimates only were produced. The indicators shown here are rare events, highlighting the necessity for cautious interpretation and utilization of findings, given the limited district-level sample sizes.",
                "Min":0,
                "Max":20,
                "Delta":1,
                "CHMin":-10.0,
                "CHMax":10.0,
                "CHDelta":1,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"District",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Lab_child": {
                "Indicator":"Prevalence of child workers",
                "Theme":"Child Protection",
                "Remark":"For child worker, census estimates were used to calculate the indicator, and only had one point in time was available.",
                "Min":0.0,
                "Max":10.0,
                "Delta":0.05,
                "CHMin":-5.0,
                "CHMax":5.0,
                "CHDelta":-0.05,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"District",
                "R1":"Census",
                "R2":"No data",
                "Y1":"2011",
                "Y2":null
            },
            "Stillbirth": {
                "Indicator":"Still birth rate",
                "Theme":"Child Health",
                "Remark":"For this indicator, district estimates only were produced. The indicators shown here are rare events, highlighting the necessity for cautious interpretation and utilization of findings, given the limited district-level sample sizes.",
                "Min":2.0,
                "Max":40.0,
                "Delta":2.0,
                "CHMin":-20.0,
                "CHMax":20.0,
                "CHDelta":2.0,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"District",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
        }
    },
    "kenya": {
        "Name": "Kenya",
        "TLC": "KEN",
        "Adm1": "County",
        "Adm2": "Sub-county",
        "Center": [0.6, 37.8],
        "Zoom": [6],
        "DistrictOnly": ['LBW', 'Min_diet', 'Sever_wast', 'Teen_Pregn', 'U_Pregn', 'Anaemia', 'ANC_4plus', 'ANC_blood', 'ANC_suppl', 'ANC_timing', 'ANC_urine', 'Breastfeed', 'C_Prev', 'Child_m', 'Labour_fem', 'NAR_prim', 'NAR_sec', 'Stunting', 'Wash_sanit', 'Wash_water', 'NMR', 'Unsafe_Ab', 'CHMR', 'Lab_child', 'Stillbirth'],
        "NoR1": ['Anaemia'],
        "NoR2": ['Teen_Pregn', 'U_Pregn'],
        "indicators": {
            "LBW": {
                "Indicator":"Low birth weight",
                "Theme":"Child Health",
                "Remark":"",
                "Min":0.0,
                "Max":42.5,
                "Delta":2.5,
                "CHMin":-25.0,
                "CHMax":25.0,
                "CHDelta":2.5,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Min_diet": {
                "Indicator":"Minimum acceptable diet",
                "Theme":"Nutrition",
                "Remark":"",
                "Min":0.0,
                "Max":48.0,
                "Delta":3.0,
                "CHMin":-32.0,
                "CHMax":24.0,
                "CHDelta":4.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Sever_wast": {
                "Indicator":"Prevalence of severe wasting",
                "Theme":"Nutrition",
                "Remark":"",
                "Min":0.0,
                "Max":42.5,
                "Delta":2.5,
                "CHMin":-22.5,
                "CHMax":25.0,
                "CHDelta":2.5,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Teen_Pregn": {
                "Indicator":"Teenage pregnancies",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":40.0,
                "Delta":2.5,
                "CHMin":-27.5,
                "CHMax":17.5,
                "CHDelta":2.5,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "U_Pregn": {
                "Indicator":"Unwanted births",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":40.0,
                "Delta":2.5,
                "CHMin":-27.5,
                "CHMax":17.5,
                "CHDelta":2.5,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Anaemia": {
                "Indicator":"Prevalence of anaemia ",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":15.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-35.0,
                "CHMax":45.0,
                "CHDelta":5.0,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "ANC_4plus": {
                "Indicator":"Antenatal care (4+ visits)",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-70.0,
                "CHMax":70.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "ANC_blood": {
                "Indicator":"Antenatal care (blood screening)",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":30.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-15.0,
                "CHMax":55.0,
                "CHDelta":5.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "ANC_suppl": {
                "Indicator":"Antenatal care (supplements)",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-70.0,
                "CHMax":70.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "ANC_timing": {
                "Indicator":"Antenatal care (timing)",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-30.0,
                "CHMax":70.0,
                "CHDelta":5.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "ANC_urine": {
                "Indicator":"Antenatal care (urine screening)",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-70.0,
                "CHMax":70.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Breastfeed": {
                "Indicator":"Exclusive breastfeeding",
                "Theme":"Nutrition",
                "Remark":"",
                "Min":20.0,
                "Max":90.0,
                "Delta":5.0,
                "CHMin":-25.0,
                "CHMax":75.0,
                "CHDelta":5.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "C_Prev": {
                "Indicator":"Modern contraceptive use",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":4.0,
                "Max":72.0,
                "Delta":4.0,
                "CHMin":-20.0,
                "CHMax":52.0,
                "CHDelta":4.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Child_m": {
                "Indicator":"Child marriage",
                "Theme":"Child Protection",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-70.0,
                "CHMax":70.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Labour_fem": {
                "Indicator":"Female labour force participation",
                "Theme":"Livelihoods",
                "Remark":"",
                "Min":4.0,
                "Max":84.0,
                "Delta":4.0,
                "CHMin":-24.0,
                "CHMax":44.0,
                "CHDelta":4.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "NAR_prim": {
                "Indicator":"Net primary school attendance",
                "Theme":"Education",
                "Remark":"",
                "Min":62.0,
                "Max":98.0,
                "Delta":2.0,
                "CHMin":-80.0,
                "CHMax":32.0,
                "CHDelta":4.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "NAR_sec": {
                "Indicator":"Net secondary school attendance",
                "Theme":"Education",
                "Remark":"",
                "Min":28.0,
                "Max":96.0,
                "Delta":4.0,
                "CHMin":-20.0,
                "CHMax":32.0,
                "CHDelta":4.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Stunting": {
                "Indicator":"Prevalence of stunting",
                "Theme":"Nutrition",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-70.0,
                "CHMax":70.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Wash_sanit": {
                "Indicator":"WASH coverage (sanitation)",
                "Theme":"WASH",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-60.0,
                "CHMax":90.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Wash_water": {
                "Indicator":"WASH coverage (water)",
                "Theme":"WASH",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-80.0,
                "CHMax":80.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "NMR": {
                "Indicator":"Neonatal mortality rate",
                "Theme":"Child Health",
                "Remark":"For this indicator, district estimates only were produced. The indicators shown here are rare events, highlighting the necessity for cautious interpretation and utilization of findings, given the limited district-level sample sizes.",
                "Min":0,
                "Max":50,
                "Delta":2.5,
                "CHMin":-25,
                "CHMax":25,
                "CHDelta":2.5,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"District",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Unsafe_Ab": {
                "Indicator":"Unsafe abortions ",
                "Theme":"Reproductive Health",
                "Remark":"For this indicator, district estimates only were produced. The indicators shown here are rare events, highlighting the necessity for cautious interpretation and utilization of findings, given the limited district-level sample sizes.",
                "Min":0,
                "Max":60,
                "Delta":3,
                "CHMin":-30,
                "CHMax":30,
                "CHDelta":3,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"District",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "CHMR": {
                "Indicator":"Child mortality rate",
                "Theme":"Child Health",
                "Remark":"For this indicator, district estimates only were produced. The indicators shown here are rare events, highlighting the necessity for cautious interpretation and utilization of findings, given the limited district-level sample sizes.",
                "Min":0,
                "Max":20,
                "Delta":1,
                "CHMin":-10.0,
                "CHMax":10.0,
                "CHDelta":1,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"District",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Lab_child": {
                "Indicator":"Prevalence of child workers",
                "Theme":"Child Protection",
                "Remark":"For child worker, census estimates were used to calculate the indicator, and only had one point in time was available.",
                "Min":0.0,
                "Max":10.0,
                "Delta":0.05,
                "CHMin":-5.0,
                "CHMax":5.0,
                "CHDelta":-0.05,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"District",
                "R1":"Census",
                "R2":"No data",
                "Y1":"2011",
                "Y2":null
            },
            "Stillbirth": {
                "Indicator":"Still birth rate",
                "Theme":"Child Health",
                "Remark":"For this indicator, district estimates only were produced. The indicators shown here are rare events, highlighting the necessity for cautious interpretation and utilization of findings, given the limited district-level sample sizes.",
                "Min":2.0,
                "Max":40.0,
                "Delta":2.0,
                "CHMin":-20.0,
                "CHMax":20.0,
                "CHDelta":2.0,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"District",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
        }
    },
    "nigeria": {
        "Name": "Nigeria",
        "TLC": "NGA",
        "Adm1": "State",
        "Adm2": "Local Government Area",
        "Center": [9.5, 8.0],
        "Zoom": [6],
        "DistrictOnly": [],
        "NoR1": [],
        "NoR2": [],
        "indicators": {
            "LBW": {
                "Indicator":"Low birth weight",
                "Theme":"Child Health",
                "Remark":"",
                "Min":0.0,
                "Max":42.5,
                "Delta":2.5,
                "CHMin":-25.0,
                "CHMax":25.0,
                "CHDelta":2.5,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Min_diet": {
                "Indicator":"Minimum acceptable diet",
                "Theme":"Nutrition",
                "Remark":"",
                "Min":0.0,
                "Max":48.0,
                "Delta":3.0,
                "CHMin":-32.0,
                "CHMax":24.0,
                "CHDelta":4.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Sever_wast": {
                "Indicator":"Prevalence of severe wasting",
                "Theme":"Nutrition",
                "Remark":"",
                "Min":0.0,
                "Max":42.5,
                "Delta":2.5,
                "CHMin":-22.5,
                "CHMax":25.0,
                "CHDelta":2.5,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Teen_Pregn": {
                "Indicator":"Teenage pregnancies",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":40.0,
                "Delta":2.5,
                "CHMin":-27.5,
                "CHMax":17.5,
                "CHDelta":2.5,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "U_Pregn": {
                "Indicator":"Unwanted births",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":40.0,
                "Delta":2.5,
                "CHMin":-27.5,
                "CHMax":17.5,
                "CHDelta":2.5,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Anaemia": {
                "Indicator":"Prevalence of anaemia ",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":15.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-35.0,
                "CHMax":45.0,
                "CHDelta":5.0,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "ANC_4plus": {
                "Indicator":"Antenatal care (4+ visits)",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-70.0,
                "CHMax":70.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "ANC_blood": {
                "Indicator":"Antenatal care (blood screening)",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":30.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-15.0,
                "CHMax":55.0,
                "CHDelta":5.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "ANC_suppl": {
                "Indicator":"Antenatal care (supplements)",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-70.0,
                "CHMax":70.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "ANC_timing": {
                "Indicator":"Antenatal care (timing)",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-30.0,
                "CHMax":70.0,
                "CHDelta":5.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "ANC_urine": {
                "Indicator":"Antenatal care (urine screening)",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-70.0,
                "CHMax":70.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Breastfeed": {
                "Indicator":"Exclusive breastfeeding",
                "Theme":"Nutrition",
                "Remark":"",
                "Min":20.0,
                "Max":90.0,
                "Delta":5.0,
                "CHMin":-25.0,
                "CHMax":75.0,
                "CHDelta":5.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "C_Prev": {
                "Indicator":"Modern contraceptive use",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":4.0,
                "Max":72.0,
                "Delta":4.0,
                "CHMin":-20.0,
                "CHMax":52.0,
                "CHDelta":4.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Child_m": {
                "Indicator":"Child marriage",
                "Theme":"Child Protection",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-70.0,
                "CHMax":70.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Labour_fem": {
                "Indicator":"Female labour force participation",
                "Theme":"Livelihoods",
                "Remark":"",
                "Min":4.0,
                "Max":84.0,
                "Delta":4.0,
                "CHMin":-24.0,
                "CHMax":44.0,
                "CHDelta":4.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "NAR_prim": {
                "Indicator":"Net primary school attendace",
                "Theme":"Education",
                "Remark":"",
                "Min":62.0,
                "Max":98.0,
                "Delta":2.0,
                "CHMin":-80.0,
                "CHMax":32.0,
                "CHDelta":4.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "NAR_sec": {
                "Indicator":"Net secondary school attendance",
                "Theme":"Education",
                "Remark":"",
                "Min":28.0,
                "Max":96.0,
                "Delta":4.0,
                "CHMin":-20.0,
                "CHMax":32.0,
                "CHDelta":4.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Stunting": {
                "Indicator":"Prevalence of stunting",
                "Theme":"Nutrition",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-70.0,
                "CHMax":70.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Wash_sanit": {
                "Indicator":"WASH coverage (sanitation)",
                "Theme":"WASH",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-60.0,
                "CHMax":90.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Wash_water": {
                "Indicator":"WASH coverage (water)",
                "Theme":"WASH",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-80.0,
                "CHMax":80.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "NMR": {
                "Indicator":"Neonatal mortality rate",
                "Theme":"Child Health",
                "Remark":"For this indicator, district estimates only were produced. The indicators shown here are rare events, highlighting the necessity for cautious interpretation and utilization of findings, given the limited district-level sample sizes.",
                "Min":0,
                "Max":50,
                "Delta":2.5,
                "CHMin":-25,
                "CHMax":25,
                "CHDelta":2.5,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"District",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Unsafe_Ab": {
                "Indicator":"Unsafe abortions ",
                "Theme":"Reproductive Health",
                "Remark":"For this indicator, district estimates only were produced. The indicators shown here are rare events, highlighting the necessity for cautious interpretation and utilization of findings, given the limited district-level sample sizes.",
                "Min":0,
                "Max":60,
                "Delta":3,
                "CHMin":-30,
                "CHMax":30,
                "CHDelta":3,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"District",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "CHMR": {
                "Indicator":"Child mortality rate",
                "Theme":"Child Health",
                "Remark":"For this indicator, district estimates only were produced. The indicators shown here are rare events, highlighting the necessity for cautious interpretation and utilization of findings, given the limited district-level sample sizes.",
                "Min":0,
                "Max":20,
                "Delta":1,
                "CHMin":-10.0,
                "CHMax":10.0,
                "CHDelta":1,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"District",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Lab_child": {
                "Indicator":"Prevalence of child workers",
                "Theme":"Child Protection",
                "Remark":"For child worker, census estimates were used to calculate the indicator, and only had one point in time was available.",
                "Min":0.0,
                "Max":10.0,
                "Delta":0.05,
                "CHMin":-5.0,
                "CHMax":5.0,
                "CHDelta":-0.05,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"District",
                "R1":"Census",
                "R2":"No data",
                "Y1":"2011",
                "Y2":null
            },
            "Stillbirth": {
                "Indicator":"Still birth rate",
                "Theme":"Child Health",
                "Remark":"For this indicator, district estimates only were produced. The indicators shown here are rare events, highlighting the necessity for cautious interpretation and utilization of findings, given the limited district-level sample sizes.",
                "Min":2.0,
                "Max":40.0,
                "Delta":2.0,
                "CHMin":-20.0,
                "CHMax":20.0,
                "CHDelta":2.0,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"District",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
        }
    }
}

export const indicatorDef = {
    "LBW": {
        "Indicator": "Low birth weight",
        "Theme": "Child health",
        "Definition": "Percentage (%) of live births in the 5 years preceding the survey weighed at birth reported as less than 2.5 kg",
        "Unit": "percent",
        "Denominator": "live births in the five (or three) years preceding the survey with a reported birth weight",
        "Proportional": false,
    },
    "Min_diet": {
        "Indicator": "Minimum acceptable diet",
        "Theme": "Nutrition",
        "Definition": "Percentage (%) of children aged 6\u201323 months who had at least minimum meal frequency and minimum diversified diet during the previous day",
        "Unit": "percent",
        "Denominator": "children aged 6 to 23 months",
        "Proportional": true,
    },
    "Sever_wast": {
        "Indicator": "Prevalence of severe wasting",
        "Theme": "Nutrition",
        "Definition": "Percentage (%) of children wasted (below -3 SD of weight for height according to the WHO\u2019s standard)",
        "Unit": "percent",
        "Denominator": "children under age five",
        "Proportional": false,
    },
    "Teen_Pregn": {
        "Indicator": "Teenage pregnancies",
        "Theme": "Reproductive Health",
        "Definition":"Percentage (%) of women 15\u201319 years old who have given birth or are pregnant with their first child over the full sample of women aged 15\u201349",
        "Unit": "percent",
        "Denominator": "women aged 15\u201349",
        "Proportional": false,
    },
    "U_Pregn": {
        "Indicator":"Unwanted births",
        "Theme":"Reproductive Health",
        "Definition":"Percentage (%) of births that are either wanted earlier or later than occurred (mistimed) or not wanted at all",
        "Unit": "percent",
        "Denominator": "",
        "Proportional": false,
    },
    "Anaemia": {
        "Indicator":"Prevalence of anaemia ",
        "Theme":"Reproductive Health",
        "Definition":"Percentage of women age 15-49 with mild, moderate or severe anaemia or with any anaemia",
        "Unit": "percent",
        "Denominator":"women interviewed (check with DHS if it's all women 15 ot 49 or a subsample of women who were asked about anaemia",
        "Proportional":false,
    },
    "ANC_4plus": {
        "Indicator":"Antenatal care (4+ visits)",
        "Theme":"Reproductive Health",
        "Definition":"Percentage (%) of women with a birth in the last 5 years, who had at least 4 antenatal care visits for most recent birth",
        "Unit": "percent",
        "Denominator":"women who had a live birth in the five (or three) years preceding the survey",
        "Proportional":true,
    },
    "ANC_blood": {
        "Indicator":"Antenatal care (blood screening)",
        "Theme":"Reproductive Health",
        "Definition":"Percentage (%) of women with a live birth in the five years preceding the survey who received antenatal care (ANC) for the most recent birth with blood sample taken.",
        "Unit": "percent",
        "Denominator":"women who had a live birth in the five (or three) years preceding the survey and received ANC",
        "Proportional":true,
    },
    "ANC_suppl": {
        "Indicator":"Antenatal care (supplements)",
        "Theme":"Reproductive Health",
        "Definition":"Among women who received antenatal care for their most recent live birth in the past 5 years, the percentage (%) that received supplements (IFA, MMS).",
        "Unit": "percent",
        "Denominator":"women who had a live birth in the five (or three) years preceding the survey",
        "Proportional":true,
    },
    "ANC_timing": {
        "Indicator":"Antenatal care (timing)",
        "Theme":"Reproductive Health",
        "Definition":"Percentage (%) of women who had a live birth in the five years preceding the survey whose first antenatal care visit was at less than 4 months ",
        "Unit": "percent",
        "Denominator": "",
        "Proportional": true,
    },
    "ANC_urine": {
        "Indicator":"Antenatal care (urine screening)",
        "Theme":"Reproductive Health",
        "Definition":"Percentage (%) of women with a live birth in the five years preceding the survey who received antenatal care (ANC) for the most recent birth with urine sample taken.",
        "Unit": "percent",
        "Denominator":"women who had a live birth in the five (or three) years preceding the survey and received ANC",
        "Proportional":true,
    },
    "Breastfeed": {
        "Indicator":"Exclusive breastfeeding",
        "Theme":"Nutrition",
        "Definition":"Percentage (%) of youngest children under 6 months who are living with their mother who are exclusively breastfed under 6 months of age",
        "Unit": "percent",
        "Denominator":"children under age 6 months",
        "Proportional":true,
    },
    "C_Prev": {
        "Indicator":"Modern contraceptive use",
        "Theme":"Reproductive Health",
        "Definition":"Percentage (%) of currently married or in union women currently using any modern method of contraception",
        "Unit": "percent",
        "Denominator":"all women",
        "Proportional":true,
    },
    "Child_m": {
        "Indicator":"Child marriage",
        "Theme":"Child Protection",
        "Definition":"Percentage (%) of women aged 20\u201324 years who were married or in a union before age 18. ",
        "Unit": "percent",
        "Denominator":"women aged 15\u201349",
        "Proportional":false,
    },
    "Labour_fem": {
        "Indicator":"Female labour force participation",
        "Theme":"Livelihoods",
        "Definition":"Percentage (%) of currently married or in union women employed in the 12 months preceding the survey.  The indicator includes those who worked in the past year, those who are currently working and those who have a job but were on leave over the last 7 days.",
        "Unit": "percent",
        "Denominator":"women currently in a union",
        "Proportional":true,
    },
    "NAR_prim": {
        "Indicator":"Net primary school attendance",
        "Theme":"Education",
        "Definition":"Number of children of official primary school age who are enrolled in primary education as a percentage (%) of the total children of the official school-age population",
        "Unit": "percent",
        "Denominator":"de facto household population of primary school age (this varies by Country)",
        "Proportional": true,
    },
    "NAR_sec": {
        "Indicator":"Net secondary school attendance",
        "Theme":"Education",
        "Definition":"Number of children of official secondary school age who are enrolled in secondary education as a percentage (%) of the total children of the official school-age population",
        "Unit": "percent",
        "Denominator":"de facto household population of secondary school age (this varies by Country)",
        "Proportional": true,
    },
    "Stunting": {
        "Indicator":"Prevalence of stunting",
        "Theme":"Nutrition",
        "Definition":"Percentage (%) of children under age five years stunted (below \u20132\u2009SD of height-for-age according to the World Health Organisation\u2019s (WHO) standard).",
        "Unit": "percent",
        "Denominator":"children under age five",
        "Proportional":false,    
    },
    "Wash_sanit": {
        "Indicator":"WASH coverage (sanitation)",
        "Theme":"WASH",
        "Definition":"Percentage (%) of the population with access to improved toilet facilities (Improved sanitation facilities include flush toilet, pit latrine (with at least a slab) or a composting toilet)",
        "Unit": "percent",
        "Denominator":"household level",
        "Proportional": true,
    },
    "Wash_water": {
        "Indicator":"WASH coverage (water)",
        "Theme":"WASH",
        "Definition":"Percentage (%) of the population with access to improved drinking water (Improved sources of drinking water include water piped into dwelling or yard/plot, to a neighbour, access to a public tap/standpipe, tube well or borehole, protected well, protected spring, rainwater, tanker truck, cart with small tank and bottled water)",
        "Unit": "percent",
        "Denominator":"household level",
        "Proportional": true,
    },
    "NMR": {
        "Indicator":"Neonatal mortality rate",
        "Theme":"Child Health",
        "Definition":"Probability (expressed per 1000 live births) of a child dying before reaching the age of 1 month over a 5-year reference period",
        "Unit": "per 1,000 live births",
        "Denominator":"admin unit level",
        "Proportional":false,
    },
    "Unsafe_Ab": {
        "Indicator":"Unsafe abortions ",
        "Theme":"Reproductive Health",
        "Definition":"Percentage (%) of pregnancies terminated either by persons lacking the necessary skills or in an environment that does not conform to minimal medical standards or both ",
        "Unit": "percent",
        "Denominator": "",
        "Proportional": false,
    },
    "CHMR": {
        "Indicator":"Child mortality rate",
        "Theme":"Child Health",
        "Definition":"Probability (expressed per 1000 children surviving their first birthday) of a child dying on or after their first birthday but before reaching the age of five years over a 5-year reference period.",
        "Unit": "per 1,000 children surviving to their first birthday",
        "Denominator": "admin unit level",
        "Proportional": false,
    },
    "Lab_child": {
        "Indicator":"Prevalence of child workers",
        "Theme":"Child Protection",
        "Definition":"Percentage (%) of children aged 5-14 years engaged in any form of work (both marginal and full-time) that may compromise their physical, mental, social or educational development",
        "Unit": "percent",
        "Denominator": "",
        "Proportional": false,
    },
    "Stillbirth": {
        "Indicator":"Still birth rate",
        "Theme":"Child Health",
        "Definition":"Number of pregnancies that lasted seven or more months and terminated in a foetal death in the five years preceding the survey per 1000 births (stillbirths plus the number of live births in the five years preceding the survey)",
        "Unit": "percent",
        "Denominator": "admin unit leve",
        "Proportional": false,
    },
}

export const StateStyle = () => {
    return {
        weight: 1,
        opacity: 0.5,
        color: 'black',
        fillOpacity: 0,
    }
}

export const StateStyle2 = () => {
  return {
      weight: 3,
      opacity: 1,
      color: 'black',
      fillOpacity: 0,
  }
}

export const DistrictStyle = () => {
  return {
      weight: 0.5,
      opacity: 1,
      color: 'black',
      fillOpacity: 0,
  }
}

export const colormaps = {
    "ciff_divergent":{"0":"#E90051","1":"#ED2641","2":"#F24C31","3":"#F67120","4":"#FB9710","5":"#FFBD00","6":"#F5C029","7":"#ECC352","8":"#E2C67A","9":"#D9C9A3","10":"#CFCCCC","11":"#AAC2C6","12":"#86B9BF","13":"#61AFB9","14":"#3DA6B2","15":"#189CAC","16":"#2B8BAC","17":"#3E7AAC","18":"#5068AD","19":"#6357AD"},
    "CIFF20":{"0":"#73B2FF","1":"#738FE5","2":"#746DCB","3":"#754BB1","4":"#5D5CAC","5":"#3F77AC","6":"#2192AC","7":"#48B0AF","8":"#91D0B5","9":"#DAEFBB","10":"#FFF4A0","11":"#FFDF64","12":"#FFCA28","13":"#FCA908","14":"#F56D22","15":"#EE313B","16":"#EA0956","17":"#F14178","18":"#F87A99","19":"#FFB3BB"},
    "CIFF20_r":{"0":"#FFB3BB","1":"#F87A99","2":"#F14178","3":"#EA0956","4":"#EE313B","5":"#F56D22","6":"#FCA908","7":"#FFCA28","8":"#FFDF64","9":"#FFF4A0","10":"#DAEFBB","11":"#91D0B5","12":"#48B0AF","13":"#2192AC","14":"#3F77AC","15":"#5D5CAC","16":"#754BB1","17":"#746DCB","18":"#738FE5","19":"#73B2FF"}
}

let pos = []
let neg = []
Object.keys(indicatorDef).forEach((key) => {
    let item = indicatorDef[key]
    if (item.Proportional) {pos.push(key)} else {neg.push(key)}
})

export const pIndicator = pos
export const nIndicator = neg

export const probOption = {
    'Show Improvement': {
      'posA': {'label':'any (>0%)', 'limit':0},
      'posB': {'label':'likely (>90%)', 'limit':90},
      'posC': {'label':'highly likely (>95%)', 'limit':95},
    },
    'Show Worsening': {
      'negA': {'label':'any (>0%)', 'limit':0},
      'negB': {'label':'likely (>90%)', 'limit':90},
      'negC': {'label':'highly likely (>95%)', 'limit':95},
    }
}
  